- hosts: all
  tasks:
    - include_tasks: "system-fonts.yml"
    - include_tasks: "system-alacritty.yml"
    - include_tasks: "system-polybar.yml"
    - include_tasks: "system-rofi.yml"
    - include_tasks: "system-picom.yml"
    - include_tasks: "system-wallpaper.yml"
    - include_tasks: "system-i3.yml"
    - include_tasks: "system-bashrc.yml"