---
- name: "copy configuration file"
  copy:
    src: "files/config/.bashrc"
    dest: "~/.bashrc"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'
  become: yes
  become_user: "{{ ansible_user_id }}"