---
- name: "delete old bashrc file"
  file:
    path: "~/.bashrc"
    state: absent
  become: yes
  become_user: "{{ ansible_user_id }}"

- name: "copy configuration file"
  copy:
    src: "files/config/.bashrc"
    dest: "~/.bashrc"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: '0644'
  become: yes
  become_user: "{{ ansible_user_id }}"