---
- name: "create local i3 directory"
  file:
    path: "~/.config/i3"
    state: directory
    mode: '0755'
  become: yes
  become_user: "{{ ansible_user_id }}"

- name: "copy configuration file"
  copy:
    src: "files/config/config"
    dest: "~/.config/i3/config"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'
  become: yes
  become_user: "{{ ansible_user_id }}"