---
- name: "create local picom directory"
  file:
    path: "~/.config/picom"
    state: directory
    mode: '0755'
  become: yes
  become_user: "{{ ansible_user_id }}"

- name: "copy configuration file"
  copy:
    src: "files/config/picom.conf"
    dest: "~/.config/picom/picom.conf"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: '0644'
  become: yes
  become_user: "{{ ansible_user_id }}"