---
- name: "create local rofi directory"
  file:
    path: "~/.config/rofi"
    state: directory
    mode: '0755'
  become: yes
  become_user: "{{ ansible_user_id }}"

- name: "create local theme directory"
  file:
    path: "~/.local/share/rofi/themes"
    state: directory
    mode: '0755'
  become: yes
  become_user: "{{ ansible_user_id }}"

- name: "unzip and copy rofi themes"
  unarchive:
    src: "files/themes/rofi-themes.zip"
    dest: "~/.local/share/rofi/themes"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'
  become: yes
  become_user: "{{ ansible_user_id }}"

- name: "copy configuration file"
  copy:
    src: "files/config/config.rasi"
    dest: "~/.config/rofi/config.rasi"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'
  become: yes
  become_user: "{{ ansible_user_id }}"