---
- name: "create local polybar directory"
  file:
    path: "~/.config/polybar"
    state: directory
    mode: '0755'
  become: yes
  become_user: "{{ ansible_user_id }}"

- name: "create local theme directory"
  file:
    path: "~/.local/share/polybar/themes"
    state: directory
    mode: '0755'
  become: yes
  become_user: "{{ ansible_user_id }}"

- name: "unzip and copy polybar themes"
  unarchive:
    src: "files/themes/polybar-themes.zip"
    dest: "~/.local/share/polybar/themes"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'
  become: yes
  become_user: "{{ ansible_user_id }}"

- name: "copy configuration file"
  copy:
    src: "files/config/config.ini"
    dest: "~/.config/polybar/config.ini"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'
  become: yes
  become_user: "{{ ansible_user_id }}"